--USERTABLE ->用户表
--USERTABLE.userid ->用户表主键

CREATE TABLE WORKFLOW
(
  ID           NUMBER(8)                        NOT NULL,
  NAME         VARCHAR2(100 BYTE),
  DESCRIPTION  VARCHAR2(1000 BYTE),
  STATUS       NUMBER(1)                        DEFAULT 1                     NOT NULL
);



ALTER TABLE WORKFLOW ADD (
  PRIMARY KEY
  (ID));



CREATE TABLE WORKFLOW_AUTH
(
  WFID   NUMBER(8),
  USRID  NUMBER(6)
);


--  There is no statement for index SYS_C0015034.
--  The object is created automatically by Oracle when the parent object is created.

ALTER TABLE WORKFLOW_AUTH ADD (
  PRIMARY KEY
  (WFID, USRID));

ALTER TABLE WORKFLOW_AUTH ADD (
  FOREIGN KEY (WFID) 
  REFERENCES WORKFLOW (ID),
  FOREIGN KEY (USRID) 
  REFERENCES USERTABLE (USERID));


CREATE TABLE WORKFLOW_NODE
(
  ID            NUMBER(8)                       NOT NULL,
  WFID          NUMBER(8)                       NOT NULL,
  NAME          VARCHAR2(100 BYTE),
  TYPE          NUMBER(1),
  DESCRIPTION   VARCHAR2(1000 BYTE),
  CFG           VARCHAR2(4000 BYTE),
  WORKTIME      NUMBER(10,2),
  WORKTIMETYPE  NUMBER(1),
  USRID         NUMBER(6),
  HANDLER       VARCHAR2(100 BYTE)
);

COMMENT ON COLUMN WORKFLOW_NODE.TYPE IS '0:start ,1,node ,2,tasknode ,3,tasknodepool,4,decision,5,fork,6 ,joinn ,9 ,end';

COMMENT ON COLUMN WORKFLOW_NODE.WORKTIMETYPE IS '1,仅工作日, 2 ,全部';

COMMENT ON COLUMN WORKFLOW_NODE.USRID IS '审批 人';




ALTER TABLE WORKFLOW_NODE ADD (
  PRIMARY KEY
  (ID));

ALTER TABLE WORKFLOW_NODE ADD (
  FOREIGN KEY (WFID) 
  REFERENCES WORKFLOW (ID));



CREATE TABLE WORKFLOW_NODE_POOL
(
  NID    NUMBER(8)                              NOT NULL,
  USRID  NUMBER(6)                              NOT NULL
);


ALTER TABLE WORKFLOW_NODE_POOL ADD (  PRIMARY KEY  (NID, USRID));

ALTER TABLE WORKFLOW_NODE_POOL ADD (
  FOREIGN KEY (NID) 
  REFERENCES WORKFLOW_NODE (ID),
  FOREIGN KEY (USRID) 
  REFERENCES USERTABLE (USERID));



CREATE TABLE WORKFLOW_NODE_VIEW
(
  ID       NUMBER(8)                            NOT NULL,
  NID      NUMBER(8),
  ORDERNO  NUMBER(4),
  CLAZZ    VARCHAR2(100 BYTE),
  CFG      VARCHAR2(4000 BYTE),
  TITLE    VARCHAR2(100 BYTE),
  TABTIP   VARCHAR2(100 BYTE),
  ICONCLS  VARCHAR2(100 BYTE)
);



ALTER TABLE WORKFLOW_NODE_VIEW ADD (
  PRIMARY KEY
  (ID));

ALTER TABLE WORKFLOW_NODE_VIEW ADD (
  FOREIGN KEY (NID) 
  REFERENCES WORKFLOW_NODE (ID));



CREATE TABLE WORKFLOW_TRANSITION
(
  ID           NUMBER(8)                        NOT NULL,
  NAME         VARCHAR2(100 BYTE),
  FROMNODE     NUMBER(8),
  TONODE       NUMBER(8),
  DESCRIPTION  VARCHAR2(200 BYTE),
  EXECUTE      VARCHAR2(200 BYTE),
  CFG          VARCHAR2(4000 BYTE)
);



ALTER TABLE WORKFLOW_TRANSITION ADD (
  PRIMARY KEY
  (ID));

ALTER TABLE WORKFLOW_TRANSITION ADD (
  FOREIGN KEY (FROMNODE) 
  REFERENCES WORKFLOW_NODE (ID),
  FOREIGN KEY (TONODE) 
  REFERENCES WORKFLOW_NODE (ID));


CREATE TABLE WORKFLOW_DOCUMENT
(
  ID          NUMBER(10)                        NOT NULL,
  WFID        NUMBER(8)                         NOT NULL,
  NID         NUMBER(8),
  USRID       NUMBER(8),
  CREATETIME  TIMESTAMP(6),
  ENDTIME     TIMESTAMP(6),
  STATUS      NUMBER(1)                         NOT NULL
);

COMMENT ON COLUMN WORKFLOW_DOCUMENT.STATUS IS '1,有效 ,0 ,无效';



ALTER TABLE WORKFLOW_DOCUMENT ADD (
  PRIMARY KEY
  (ID));

ALTER TABLE WORKFLOW_DOCUMENT ADD (
  FOREIGN KEY (WFID) 
  REFERENCES WORKFLOW (ID),
  FOREIGN KEY (NID) 
  REFERENCES WORKFLOW_NODE (ID));



CREATE TABLE WORKFLOW_DOCUMENT_STEPS
(
  ID          NUMBER(10)                        NOT NULL,
  DID         NUMBER(10),
  NID         NUMBER(8),
  USRID       NUMBER(6),
  ENTERDATE   TIMESTAMP(6),
  SUBMITDATE  TIMESTAMP(6),
  BACKDATE    TIMESTAMP(6),
  STATUS      NUMBER(1)                         NOT NULL,
  MSG         VARCHAR2(4000 BYTE)
);

COMMENT ON COLUMN WORKFLOW_DOCUMENT_STEPS.STATUS IS '0,正常 ,1,提交,-1,回退 ,4,挂起';

COMMENT ON COLUMN WORKFLOW_DOCUMENT_STEPS.MSG IS '意见';



ALTER TABLE WORKFLOW_DOCUMENT_STEPS ADD (
  PRIMARY KEY
  (ID));

ALTER TABLE WORKFLOW_DOCUMENT_STEPS ADD (
  FOREIGN KEY (DID) 
  REFERENCES WORKFLOW_DOCUMENT (ID),
  FOREIGN KEY (NID) 
  REFERENCES WORKFLOW_NODE (ID),
  FOREIGN KEY (USRID) 
  REFERENCES USERTABLE (USERID));



CREATE TABLE WORKFLOW_DOCUMENT_STEPS_SUSP
(
  ID      NUMBER(10)                            NOT NULL,
  DNID    NUMBER(10),
  DODATE  TIMESTAMP(6)                          NOT NULL,
  STATUS  NUMBER(1)                             NOT NULL
);

COMMENT ON COLUMN WORKFLOW_DOCUMENT_STEPS_SUSP.STATUS IS '0解挂,1挂起';



ALTER TABLE WORKFLOW_DOCUMENT_STEPS_SUSP ADD (
  PRIMARY KEY
  (ID));

ALTER TABLE WORKFLOW_DOCUMENT_STEPS_SUSP ADD (
  FOREIGN KEY (DNID) 
  REFERENCES WORKFLOW_DOCUMENT_STEPS (ID));
  
  
  
  

CREATE SEQUENCE SEQ_WORKFLOW
  START WITH 10000000
  MAXVALUE 99999999
  MINVALUE 10000000
  NOCYCLE
  NOCACHE
  NOORDER;



CREATE SEQUENCE SEQ_WORKFLOW_DOCUMENT_ID
  START WITH 1000000000
  MAXVALUE 9999999999999999999999999999
  MINVALUE 1000000000
  NOCYCLE
  NOCACHE
  NOORDER;



CREATE SEQUENCE SEQ_WORKFLOW_DOCUMENT_STEPS_ID
  START WITH 1000000000
  MAXVALUE 9999999999999999999999999999
  MINVALUE 1000000000
  NOCYCLE
  NOCACHE
  NOORDER;
  
